name: Deploy Container via PR

# Controls when the action will run. 
on:
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  issue_ops:
    name: "Extract Issue Ops Values From PR"
    runs-on: ubuntu-latest
    outputs:
        app_service_name: ${{ steps.set_env_values.outputs.app_service_name }}
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      ## Issue Ops - Extract information from JSON - Local Action
      - name: Extract Issue Demo Specification
        id: issue_body
        uses: peter-murray/issue-body-parser-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ github.event.number }}
      
      - name: Set JSON Variables as Output Values
        id: set_env_values
        run: | 
          for s in $(echo '${{ steps.issue_body.outputs.payload }}' | jq -r "to_entries|map(\"\(.key)::\(.value|tostring)\")|.[]" ); do
          echo '::set-output name='"$s"''
          done
          
      - name: Set App Service Output Step
        id: app_serviceName
        run: echo "::set-output name=app_serviceName::${{ steps.set_env_values.outputs.app_service_name }}"

  build-and-test:
    name: ðŸ§ª Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x']
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: npm install, build, and test
      run: |
        # Build and test the project
        npm install
        npm run build --if-present
        npm run test --if-present
    
  docker-build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    needs: [issue_ops, build-and-test]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/octodemo/demoday-node:${{ github.event.pull_request.head.sha || github.sha }}

  azure-deployment-staging:
    name: ðŸ“¦ Azure deployment staging
    runs-on: ubuntu-latest
    needs: [issue_ops, build-and-test, docker-build-and-push]
    environment:
      name: STAGING
      url: "https://${{ needs.issue_ops.outputs.app_service_name }}-staging.azurewebsites.net/"
    steps:
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ needs.issue_ops.outputs.app_service_name }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'ghcr.io/octodemo/demoday-node:${{ github.event.pull_request.head.sha || github.sha }}'
        slot-name: staging
  
  validate-site-staging:
    name: âœ”ï¸ Validate Deployment - Staging
    runs-on: ubuntu-latest
    needs: azure-deployment-staging

    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.2
      with:
        # Check the following URLs one by one sequentially
        url: https:/${{ needs.issue_ops.outputs.app_service_name }}-staging.azurewebsites.net/|https://${{ needs.issue_ops.outputs.app_service_name }}-staging.azurewebsites.net/user/james-leha
        # Follow redirects, or just report success on 3xx status codes
        follow-redirect: no # Optional, defaults to "no"
        # Fail this action after this many failed attempts
        max-attempts: 3 # Optional, defaults to 1
        # Delay between retries
        retry-delay: 5s # Optional, only applicable to max-attempts > 1

  azure-deployment-production:
    name: ðŸ“¦ Azure deployment production
    runs-on: ubuntu-latest
    needs: [issue_ops, build-and-test, docker-build-and-push, azure-deployment-staging, validate-site-staging]
    environment:
      name: PRODUCTION
      url: "https://${{ needs.issue_ops.outputs.app_service_name }}.azurewebsites.net/"
    steps:
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ needs.issue_ops.outputs.app_service_name }}
        publish-profile: ${{ secrets.AZURE_CREDS }}
        images: 'ghcr.io/octodemo/demoday-node:${{ github.event.pull_request.head.sha || github.sha }}'
        slot-name: production

  validate-site-production:
    name: âœ”ï¸ Validate Deployment - Production
    runs-on: ubuntu-latest
    needs: azure-deployment-production

    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.2
      with:
        # Check the following URLs one by one sequentially
        url: https:/${{ needs.issue_ops.outputs.app_service_name }}.azurewebsites.net/|https://${{ needs.issue_ops.outputs.app_service_name }}.azurewebsites.net/user/james-leha
        # Follow redirects, or just report success on 3xx status codes
        follow-redirect: no # Optional, defaults to "no"
        # Fail this action after this many failed attempts
        max-attempts: 3 # Optional, defaults to 1
        # Delay between retries
        retry-delay: 5s # Optional, only applicable to max-attempts > 1